define([], function () {

    'use strict';

    return {
        commodities: {
            AGR: "Cereals",
            FUE: "Mineral fuels, mineral oils and products of their distillation: bituminous substances: mineral waxes",
            MAN: "Miscellaneous manufactured articles"
        },
        trades: {
            IMP: "Import",
            EXP: "Export"
        },
        countries: {
            "1": "Afghanistan",
            "10": "Antarctica",
            "101": "Guam",
            "103": "Guatemala",
            "105": "Guinea-Bissau",
            "106": "Guinea",
            "107": "Guyana",
            "108": "Haiti",
            "109": "Heard Island and McDonald Islands",
            "11": "Antigua and Barbuda",
            "110": "Holy See (Vatican City State)",
            "111": "Honduras",
            "113": "Hungary",
            "114": "Iceland",
            "115": "India",
            "116": "Indonesia",
            "117": "Iran",
            "118": "Iraq",
            "119": "Ireland",
            "12": "Argentina",
            "121": "Israel",
            "122": "Italy",
            "123": "Jamaica",
            "126": "Japan",
            "13": "Armenia",
            "130": "Jordan",
            "132": "Kazakhstan",
            "133": "Kenya",
            "135": "Kiribati",
            "137": "Kuwait",
            "138": "Kyrgyzstan",
            "139": "Lao People's Dem. Rep.",
            "14": "Aruba",
            "140": "Latvia",
            "141": "Lebanon",
            "142": "Lesotho",
            "144": "Liberia",
            "145": "Libya",
            "147": "Lithuania",
            "148": "Luxembourg",
            "150": "Madagascar",
            "152": "Malawi",
            "153": "Malaysia",
            "154": "Maldives",
            "155": "Mali",
            "156": "Malta",
            "157": "Marshall Isds",
            "159": "Mauritania",
            "160": "Mauritius",
            "161": "Mayotte",
            "162": "Mexico",
            "163": "FS Micronesia",
            "165": "Rep. of Moldova",
            "167": "Mongolia",
            "168": "Montserrat",
            "169": "Morocco",
            "17": "Australia",
            "170": "Mozambique",
            "171": "Myanmar",
            "172": "Namibia",
            "173": "Nauru",
            "175": "Nepal",
            "176": "Neth. Antilles",
            "177": "Netherlands",
            "178": "New Caledonia",
            "179": "New Zealand",
            "18": "Austria",
            "180": "Nicaragua",
            "181": "Niger",
            "182": "Nigeria",
            "183": "Niue",
            "185": "N. Mariana Isds",
            "186": "Norway",
            "187": "Oman",
            "188": "Pakistan",
            "189": "Palau",
            "19": "Azerbaijan",
            "191": "Panama",
            "192": "Papua New Guinea",
            "194": "Paraguay",
            "195": "Peru",
            "196": "Philippines",
            "198": "Poland",
            "199": "Portugal",
            "20": "Bahamas",
            "201": "Qatar",
            "202": "Rep. of Korea",
            "203": "Romania",
            "204": "Russian Federat,ion",
            "205": "Rwanda",
            "208": "Saint Kitts and Nevis",
            "209": "Saint Lucia",
            "21": "Bahrain",
            "211": "Saint Vincent and the Grenadines",
            "213": "San Marino",
            "214": "Sao Tome and Principe",
            "215": "Saudi Arabia",
            "217": "Senegal",
            "219": "Serbia and Montenegro",
            "220": "Seychelles",
            "221": "Sierra Leone",
            "222": "Singapore",
            "223": "Slovakia",
            "224": "Slovenia",
            "225": "Solomon Isds",
            "226": "Somalia",
            "227": "South Africa",
            "228": "South Georgia and the South Sandwich Islands",
            "229": "Spain",
            "23": "Bangladesh",
            "231": "Sri Lanka",
            "233": "Suriname",
            "235": "Swaziland",
            "236": "Sweden",
            "237": "Switzerland",
            "238": "Syria",
            "239": "Tajikistan",
            "24": "Barbados",
            "240": "Thailand",
            "241": "TFYR of Macedonia",
            "242": "Timor-Leste",
            "243": "Togo",
            "245": "Tonga",
            "246": "Trinidad and Tobago",
            "248": "Tunisia",
            "24885": "China, Macao SAR",
            "249": "Turkey",
            "250": "Turkmenistan",
            "251": "Turks and Caicos Isds",
            "252": "Tuvalu",
            "253": "Uganda",
            "254": "Ukraine",
            "255": "United Arab Emirates",
            "256": "United Kingdom",
            "257": "United Rep. of Tanzania",
            "259": "USA",
            "26": "Belarus",
            "260": "Uruguay",
            "261": "Uzbekistan",
            "262": "Vanuatu",
            "263": "Venezuela",
            "264": "Viet Nam",
            "2647": "Montenegro",
            "2648": "Serbia",
            "268": "Western Sahara",
            "269": "Yemen",
            "27": "Belgium",
            "270": "Zambia",
            "271": "Zimbabwe",
            "28": "Belize",
            "29": "Benin",
            "3": "Albania",
            "30": "Bermuda",
            "31": "Bhutan",
            "33": "Bolivia (Plurinational State of)",
            "33364": "China, Hong Kong SAR",
            "34": "Bosnia Herzegovina",
            "35": "Botswana",
            "36": "Bouvet Island",
            "37": "Brazil",
            "38": "Br. Indian Ocean Terr.",
            "39": "Br. Virgin Isds",
            "4": "Algeria",
            "40": "Brunei Darussalam",
            "40765": "Egypt",
            "41": "Bulgaria",
            "42": "Burkina Faso",
            "43": "Burundi",
            "44": "Cambodia",
            "45": "Cameroon",
            "46": "Canada",
            "47": "Cabo Verde",
            "48": "Cayman Isds",
            "49": "Central African Rep.",
            "5": "American Samoa",
            "50": "Chad",
            "51": "Chile",
            "53": "China",
            "54": "Christmas Isds",
            "56": "Cocos Isds",
            "57": "Colombia",
            "58": "Comoros",
            "59": "Congo",
            "6": "Sudan",
            "60": "Cook Isds",
            "61": "Costa Rica",
            "62": "Croatia",
            "63": "Cuba",
            "64": "Cyprus",
            "65": "Czech Rep.",
            "66": "Côte d'Ivoire",
            "67": "Dem. People's Rep. of Korea",
            "68": "Dem. Rep. of the Congo",
            "69": "Denmark",
            "7": "Andorra",
            "70": "Djibouti",
            "71": "Dominica",
            "72": "Dominican Rep.",
            "73": "Ecuador",
            "74": "South Sudan",
            "75": "El Salvador",
            "76": "Equatorial Guinea",
            "77": "Eritrea",
            "78": "Estonia",
            "79": "Ethiopia",
            "8": "Angola",
            "81": "Falkland Isds (Malvinas)",
            "82": "Faeroe Isds",
            "83": "Fiji",
            "84": "Finland",
            "85": "France",
            "87": "French Polynesia",
            "88": "Fr. South Antarctic Terr.",
            "89": "Gabon",
            "9": "Anguilla",
            "90": "Gambia",
            "92": "Georgia",
            "93": "Germany",
            "94": "Ghana",
            "95": "Gibraltar",
            "97": "Greece",
            "98": "Greenland",
            "99": "Grenada",
            "WLD": "World"
        }
    }
})